### ISSUE TITLE
柱状图放进xml中报NoSuchElementException，和NullPointerException，如何解决

### ISSUE THREAD

**Issue by qingchen1016** [teddyisme/LCharts-android#7]
您好，感谢提供好用的图表，使用柱状图遇到如题的问题，请帮忙看看，谢谢
![1563114368(1)](https://user-images.githubusercontent.com/22384203/61185001-74633d00-a686-11e9-861c-510f58b90f71.jpg)
![1563114389(1)](https://user-images.githubusercontent.com/22384203/61185002-74633d00-a686-11e9-9b31-463b2b467d3b.jpg)
我使用的版本是implementation 'com.lixs.charts:charts:1.0.7'
minSdkVersion 19
targetSdkVersion 27
classpath 'com.android.tools.build:gradle:3.0.1'
https\://services.gradle.org/distributions/gradle-4.1-all.zip
Android Studio 3.0.1

**Comment by teddyisme** [comment]
> 您好，感谢提供好用的图表，使用柱状图遇到如题的问题，请帮忙看看，谢谢
> ![1563114368(1)](https://user-images.githubusercontent.com/22384203/61185001-74633d00-a686-11e9-861c-510f58b90f71.jpg)
> ![1563114389(1)](https://user-images.githubusercontent.com/22384203/61185002-74633d00-a686-11e9-9b31-463b2b467d3b.jpg)
> 我使用的版本是implementation 'com.lixs.charts:charts:1.0.7'
> minSdkVersion 19
> targetSdkVersion 27
> classpath 'com.android.tools.build:gradle:3.0.1'
> https://services.gradle.org/distributions/gradle-4.1-all.zip
> Android Studio 3.0.1

你好，请查看demo中添加数据操作。。。没有数据的初始化会报这个错，不好意思。

**Comment by teddyisme** [comment]
你好，请查看demo中添加数据操作。。。没有数据的初始化会报这个错，不好意思。

**Comment by qingchen1016** [comment]
LBarChartView.setDragInerfaces(new DragInerfaces() {
            @Override
            public void onEnd() {
                final List<Double> datas = new ArrayList<>();
                final List<String> description = new ArrayList<>();
                datas.add(40d);
                datas.add(15d);
                datas.add(38d);
                datas.add(60d);
                datas.add(10d);

                description.add("one");
                description.add("two");
                description.add("three");
                description.add("four");
                description.add("five");
                LBarChartView.addEndMoreData(datas, description);
            }

            @Override
            public void onStart() {

            }
        });


您是说这个操作吗？有点没看明白这个添加的数据和外层
LBarChartView.setDatas(datas, description, true);
这个添加的数据的区别是啥

感谢回复

**Comment by teddyisme** [comment]
我刚新建了项目试了，只setDatas也是没有问题的。setDragInerfaces这个是设置监听滑动




------------------ 原始邮件 ------------------
发件人: "清晨"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 下午2:36
收件人: "teddyisme/LCharts-android"<LCharts-android@noreply.github.com>; 
抄送: "各木"<41323320@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [teddyisme/LCharts-android] 柱状图放进xml中报NoSuchElementException，和NullPointerException，如何解决 (#7)




LBarChartView.setDragInerfaces(new DragInerfaces() {
 @override
 public void onEnd() {
 final List datas = new ArrayList<>();
 final List description = new ArrayList<>();
 datas.add(40d);
 datas.add(15d);
 datas.add(38d);
 datas.add(60d);
 datas.add(10d);
             description.add("one");             description.add("two");             description.add("three");             description.add("four");             description.add("five");             LBarChartView.addEndMoreData(datas, description);         }         @Override         public void onStart() {         }     });  
您是说这个操作吗？有点没看明白这个添加的数据和外层
 LBarChartView.setDatas(datas, description, true);
 这个添加的数据的区别是啥
 
感谢回复

**Comment by qingchen1016** [comment]
完全按照demo里的，数据也没变，运行报错 
![image](https://user-images.githubusercontent.com/22384203/61199522-d7011b00-a710-11e9-94b7-88d7a04caf32.png)

把setDragInerfaces  这个去掉也是报一样的错

**Comment by qingchen1016** [comment]
方便把您运行成功的demo发一下邮箱吗？

这个项目clone到本地后报错
![image](https://user-images.githubusercontent.com/22384203/61199624-4119c000-a711-11e9-895d-1e82a0686a12.png)

**Comment by qingchen1016** [comment]
可以了，原来一开始是我把setDatas写的太靠后，应该在初始化空间的时候就接着设置数据

再次感谢感谢

**Comment by qingchen1016** [comment]
第二次设置数据时，左边栏对应数据好像还有点问题
为了不让初始化奔溃，初始化控件时设置了  datas.add(1d);
获取到网络加载的数据后，重新设置了数据，但是左边栏没有根据新数据的大小值变化，还是（1d）
不知是否是我有哪里写错了呢？
![image](https://user-images.githubusercontent.com/22384203/61203033-d02bd580-a71b-11e9-97c8-b5506847cf00.png)

**Comment by teddyisme** [comment]
不好意思，项目时间有点长，我只能再抽空看看了，精力达不到。抱歉------------------ 原始邮件 ------------------
发件人: "清晨"<notifications@github.com>
发送时间: 2019年7月15日(星期一) 下午4:16
收件人: "teddyisme/LCharts-android"<LCharts-android@noreply.github.com>;
抄送: "teddyisme"<41323320@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [teddyisme/LCharts-android] 柱状图放进xml中报NoSuchElementException，和NullPointerException，如何解决 (#7)



第&#x4E8C;次设置数据时，左边栏对应数据好像还有点问题
 为了不让初始化奔溃，初始化控&#x4EF6;时设置了  datas.add(1d);
 获取到网络加载的数据后，重新设置了数据，但是左边栏没有根据新数据的大小值变化，还是（1d）
 不知是否是我有哪里写错了呢？
 
 
&mdash;

**Comment by qingchen1016** [comment]
好的，没关系。再次感谢提供好用的库和您的回复。
